name: New changes validation

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  cache-V:
    runs-on: ubuntu-latest
    steps:
      - name: Check if V is cached
        id: check-v-cache
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09

      - if: ${{ steps.check-v-cache.outputs.cache-hit != 'true' }}
        name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - if: ${{ steps.check-v-cache.outputs.cache-hit != 'true' }}
        name: Cache Vlang
        uses: actions/cache/save@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09

  simple-build:
    needs: cache-V
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #        trimming: [ null , -skip-unused ] NOTE: -skip-unused doesn't work with UI apps, bug was reported
        #        memory-management: [ null , -autofree ] NOTE: -autofree doesn't work with UI apps, bug was reported
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: ${{ matrix.example-to-build }} build
        run: v ${{ matrix.example-to-build }}/

  cache-clang:
    needs: simple-build
    runs-on: ubuntu-latest
    steps:
      - name: Check if LLVM and Clang is cached
        id: check-llvm-cache
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/llvm
          key: llvm-15

      - if: ${{ steps.check-llvm-cache.outputs.cache-hit != 'true' }}
        name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '15'

      - if: ${{ steps.check-llvm-cache.outputs.cache-hit != 'true' }}
        name: Cache LLVM and Clang
        uses: actions/cache/save@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/llvm
          key: llvm-15

  different-compilers:
    needs: cache-clang
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
        #        trimming: [ null , -skip-unused ] NOTE: -skip-unused doesn't work with UI apps, bug was reported
        #        memory-management: [ null , -autofree ] NOTE: -autofree doesn't work with UI apps, bug was reported
        optimization: [ null , -prod ]
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - if: ${{ matrix.compiler == 'gcc' }}
        name: Set up GCC
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y build-essential

      - if: ${{ matrix.compiler == 'clang' }}
        name: Restore LLVM and Clang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/llvm
          key: llvm-15
          fail-on-cache-miss: true

      - if: ${{ matrix.compiler == 'clang' }}
        name: Setup LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '15'
          cached: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: ${{ matrix.compiler }} ${{ matrix.optimization }} ${{ matrix.example-to-build }} build
        run: v -cc ${{ matrix.compiler }} ${{ matrix.optimization }} ${{ matrix.example-to-build }}/

  clang-sanitizers:
    needs: different-compilers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [ address, thread, memory, undefined, leak ]
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - name: Restore LLVM and Clang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/llvm
          key: llvm-15
          fail-on-cache-miss: true

      - name: Setup LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '15'
          cached: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Clang ${{ matrix.sanitizer }} sanitizer - ${{ matrix.example-to-build }} project
        run: v -cc clang -cflags -fsanitize=${{ matrix.sanitizer }} ${{ matrix.example-to-build }}/

  gcc-sanitizers:
    needs: different-compilers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [ thread, leak ]
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - name: Set up GCC
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y build-essential

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: GCC ${{ matrix.sanitizer }} sanitizer - ${{ matrix.example-to-build }} project
        run: v -cc gcc -cflags -fsanitize=${{ matrix.sanitizer }} ${{ matrix.example-to-build }}/

  gcc-address-sanitizers:
    needs: different-compilers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - name: Set up GCC
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y build-essential

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: GCC address sanitizer - ${{ matrix.example-to-build }} project
        run: v -cc gcc -cflags -fsanitize=address -cflags -fsanitize-address-use-after-scope -cflags -fsanitize=pointer-compare -cflags -fsanitize=pointer-subtract ${{ matrix.example-to-build }}/

  gcc-undefined-sanitizers:
    needs: different-compilers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - name: Set up GCC
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y build-essential

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: GCC undefined sanitizer - ${{ matrix.example-to-build }} project
        run: v -cc gcc -cflags -fsanitize=undefined -cflags -fsanitize=shift -cflags -fsanitize=shift-exponent -cflags -fsanitize=shift-base -cflags -fsanitize=integer-divide-by-zero -cflags -fsanitize=unreachable -cflags -fsanitize=vla-bound -cflags -fsanitize=null -cflags -fsanitize=return -cflags -fsanitize=signed-integer-overflow -cflags -fsanitize=bounds -cflags -fsanitize=bounds-strict -cflags -fsanitize=alignment -cflags -fsanitize=object-size -cflags -fsanitize=float-divide-by-zero -cflags -fsanitize=float-cast-overflow -cflags -fsanitize=nonnull-attribute -cflags -fsanitize=returns-nonnull-attribute -cflags -fsanitize=bool -cflags -fsanitize=enum -cflags -fsanitize=vptr -cflags -fsanitize=pointer-overflow -cflags -fsanitize=builtin ${{ matrix.example-to-build }}/

  vab-compilation:
    needs: [ clang-sanitizers, gcc-sanitizers, gcc-address-sanitizers, gcc-undefined-sanitizers ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          sdk-version: 31
          build-tools-version: '33.0.2'
          ndk-version: '25.2.9519653'
          cache-disabled: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Install vab
        run: |
          v install vab
          v -g ~/.vmodules/vab
          sudo ln -s ~/.vmodules/vab/vab /usr/local/bin/vab

      - name: Build APK - ${{ matrix.example-to-build }} project
        run: vab --min-sdk-version 26 --api 31 --archs 'arm64-v8a' -v 3 ${{ matrix.example-to-build }}/

  linux-to-other-platforms-compilation:
    needs: [ clang-sanitizers, gcc-sanitizers, gcc-address-sanitizers, gcc-undefined-sanitizers ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - name: Install MinGW-w64
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y gcc-mingw-w64-x86-64

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Build Windows executable - ${{ matrix.example-to-build }} project
        run: v -os windows ${{ matrix.example-to-build }}/

  check-formatting:
    needs: [ vab-compilation, linux-to-other-platforms-compilation ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Check formatting - ${{ matrix.example-to-build }} project
        run: v fmt -verify ${{ matrix.example-to-build }}/

  check-docs:
    needs: [ vab-compilation, linux-to-other-platforms-compilation ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Check markdown line length & code examples
        run: v check-md -hide-warnings .

      - name: Check public methods without documentation - ${{ matrix.example-to-build }} project
        run: v missdoc --exclude src/tests/ --verify ${{ matrix.example-to-build }}/

  vet-check:
    needs: [ vab-compilation, linux-to-other-platforms-compilation ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example-to-build: [ cli_counter, ui_counter ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.09
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.09'

      - name: Install UI module
        run: v install ui

      - name: Install graphic libs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libxi-dev libxcursor-dev libgl-dev

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Check code with vet - ${{ matrix.example-to-build }} project
        run: v vet -W ${{ matrix.example-to-build }}/
